{
 "title": "Kube Inventory",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "alert_outdated_pods", "label": "Outdated Pods", "query": "5" },
   { "name": "alert_stale_applications", "label": "Stale Applications", "query": "90" },
   { "name": "alert_abandoned_applications", "label": "Abandoned Applications", "query": "90" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "repo",
    "label": "Repo",
    "query": {
     "query": "label_values(kube_inventory_pod_versions_to_latest_release,repo)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\"},exported_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_inventory_pod_versions_to_latest_release{exported_namespace=~\"$namespace\"},name)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_inventory_pod_versions_to_latest_release{exported_namespace=~\"$namespace\", name=~\"$pod\"},container_name)"
    }
   },
   {
    "name": "silenced",
    "label": "Silenced",
    "query": {
     "query": "label_values(kube_inventory_pod_versions_to_latest_release,silenced)"
    }
   },
   { "name": "current_release_age", "label": "Current Release Age", "query": "0,1,2,5,10,15,20,30,60,90" },
   { "name": "latest_release_age", "label": "Latest Release Age", "query": "0,1,2,5,10,15,20,30,60,90" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repos",
   "type": "stat",
   "description": "Total of inventories Github repositories from applications running in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (repo) (\n    max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n      kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\"}\n      )\n    and on(exported_namespace, name, container_name)\n    (\n      (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n    )\n    and on(exported_namespace, name, container_name)\n    (\n      (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "Number of namespaces that contains inventoried applications.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (exported_namespace) (\n    max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n      kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\"}\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n      )\n    )\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inv. Pods",
   "type": "stat",
   "description": "Inventoried Pods.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (name) (\n    max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n      kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\"}\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n      )\n    )\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inv. Pods (%)",
   "type": "gauge",
   "description": "Percentage of inventoried pods",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (name) (\n    max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n      kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\"}\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n      )\n    )\n  )\n  / \nsum(kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Number of inventoried containers.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (container_name) (\n    max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n      kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\"}\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n      )\n    )\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Silenced",
   "type": "stat",
   "description": "Inventoried applications that NOT trigger alerts.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n  count(kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=\"true\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods (Total)",
     "type": "stat",
     "description": "Total of Pods in the cluster.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(kube_pod_info)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Inv. Pods",
     "type": "stat",
     "description": "Inventoried Pods.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  sum by (name) (\n    max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n      kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\"}\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n      )\n    )\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inv. Pods (%)",
     "type": "gauge",
     "description": "Percentage of inventoried pods",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  sum by (name) (\n    max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n      kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\"}\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n      )\n      and on(exported_namespace, name, container_name)\n      (\n        (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n      )\n    )\n  )\n  / \nsum(kube_pod_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Not Inv. Pods",
     "type": "stat",
     "description": "Number of Pods that were not inventoried.",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info\nunless on(namespace, pod)\nlabel_replace(\n  label_replace(\n    kube_inventory_pod_versions_to_latest_release,\n    \"pod\", \"$1\", \"name\", \"(.*)\"\n  ),\n  \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"\n))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Not Inventoried Pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "kube_pod_info\nunless on(namespace, pod)\nlabel_replace(\n  label_replace(\n    kube_inventory_pod_versions_to_latest_release,\n    \"pod\", \"$1\", \"name\", \"(.*)\"\n  ),\n  \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outdated Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n    kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"} > $alert_outdated_pods\n    )\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Staled Apps",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n    kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"}\n    )\n    and on(exported_namespace, name, container_name)\n    (\n      ((time() - kube_inventory_pod_current_release_timestamp) > ($alert_stale_applications * 24 * 3600))\n    )\n    and on(exported_namespace, name, container_name)\n    (\n      (time() - kube_inventory_pod_latest_release_timestamp) < ($alert_abandoned_applications * 24 * 3600)\n    )\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Abandoned Apps",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n    ((time() - kube_inventory_pod_latest_release_timestamp{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"}) > ($alert_abandoned_applications * 24 * 3600))\n    )\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outdated Pods",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n    kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"} > $alert_outdated_pods\n    )\n  )\n  / sum(kube_pod_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Staled Apps",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n    kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"}\n    )\n    and on(exported_namespace, name, container_name)\n    (\n      ((time() - kube_inventory_pod_current_release_timestamp) > ($alert_stale_applications * 24 * 3600))\n    )\n    and on(exported_namespace, name, container_name)\n    (\n      (time() - kube_inventory_pod_latest_release_timestamp) < ($alert_abandoned_applications * 24 * 3600)\n    )\n  )\n  / sum(kube_pod_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Abandoned Apps",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n    ((time() - kube_inventory_pod_latest_release_timestamp{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"}) > ($alert_abandoned_applications * 24 * 3600))\n    )\n  )\n  / sum(kube_pod_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outdated Pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n  kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"} > $alert_outdated_pods\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Staled Apps",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n  kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"}\n  )\n  and on(exported_namespace, name, container_name)\n  (\n    ((time() - kube_inventory_pod_current_release_timestamp) > ($alert_stale_applications * 24 * 3600))\n  )\n  and on(exported_namespace, name, container_name)\n  (\n    (time() - kube_inventory_pod_latest_release_timestamp) < ($alert_abandoned_applications * 24 * 3600)\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Abandoned Apps",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n  kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"}\n  )\n  and on(exported_namespace, name, container_name)\n  (\n    (time() - kube_inventory_pod_latest_release_timestamp) > ($alert_abandoned_applications * 24 * 3600)\n  )\n  ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inventoried Applications",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "max by (repo, exported_namespace, name, container_name, silenced, current_release_name, latest_release_date, latest_release_name, current_release_date) (\n  kube_inventory_pod_versions_to_latest_release{repo=~\"$repo\", exported_namespace=~\"$namespace\", name=~\"$pod\", container_name=~\"$container\", silenced=~\"$silenced\"}\n  )\nand on(exported_namespace, name, container_name)\n(\n  (time() - kube_inventory_pod_current_release_timestamp) > ($current_release_age * 24 * 3600)\n)\nand on(exported_namespace, name, container_name)\n(\n  (time() - kube_inventory_pod_latest_release_timestamp) > ($latest_release_age * 24 * 3600)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}